name: Publish NuGet

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'NuGet version'
        required: true

# github.event.inputs.version
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v2
      - name: âœ¨ Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: ğŸ­ Restore dependencies
        run: dotnet restore
      - name: ğŸ§± Build
        run: dotnet build --no-restore
      - name: ğŸ› Test
        run: dotnet test --no-build --verbosity normal
      - name: ğŸ†š Get NuGet version
        id: mainversion
        shell: pwsh
        run: |
          $split = "${{ github.event.inputs.version }}" -split "-",2
          $mainver = $split[0]
          echo "::set-output name=value::$mainver"
      - name: ğŸ“¦ NuGet Pack
        run: dotnet pack /p:Version='${{ github.event.inputs.version }}' /p:PackageVersion='${{ github.event.inputs.version }}' /p:AssemblyVersion='${{ steps.mainversion.outputs.value }}' /p:FileVersion='${{ steps.mainversion.outputs.value }}' /p:InformationalVersion='${{ github.event.inputs.version }}'
      - name: ğŸ“¢ NuGet Push
        run: dotnet nuget push ./CommandLine/nupkg/scrap.*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
      - name: ğŸ· Tag commit and push
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git tag v${{ github.event.inputs.version }}
          git push origin --tags